#!/usr/bin/env bash
#Script that loops from 1 to 10 and does more

j=1
while (( j<=10 ));
do
	if (( j == 4 ));
	then
		echo "bad luck"
	elif (( j == 8 ));
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( j++ ))
done
