#!/usr/bin/env bash
#Script that displays the tiÂme for 12 hours and 59 minutes:

hours=0

while (( hours<13 ))
do
	echo "Hour: $hours"
	minute=1
	while (( minute<=59 ))
	do
		echo "$minute"
		minute=$((minute+1))
	done
	hours=$((hours+1))
done
